networks:
  test-project-network:
    name: test-project-network

services:
  tp-nginx:
    container_name: tp-nginx
    image: nginx
    ports:
      - 80:80
    volumes:
      - c://download/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf #Необходимо изменить папке проекта
      - c://download/docker/www:/var/www/public_html #Необходимо изменить папке проекта
    networks:
      - test-project-network
    depends_on:
      - tp-phpfpm
  tp-phpfpm:
    container_name: tp-phpfpm
    build: ./images/php
    volumes:
      - c://download/docker/www:/var/www/public_html #Необходимо изменить папке проекта
    networks:
      - test-project-network
